version: '3.4'

services:
  reactapp:
    image: reactapp
    build:
      context: reactapp
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  dotnetdemowebapi:
    image: dotnetdemowebapi
    build:
      context: .
      dockerfile: DotNetDemo.WebApi/Dockerfile
    ports:
      - 5000:5000
