version: '3.4'

services:
  reactapp:
    image: reactapp
    build:
      context: reactapp
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
  dotnetdemowebapi:
    image: dotnetdemowebapi
    build:
      context: .
      dockerfile: DotNetDemo.WebApi/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
